apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-api
  name: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-api
    spec:
      containers:
      - image: docker.io/xxzk/flask-homework
        name: flask-homework
        resources: {}
status: {}
