apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask-api
  name: flask-api
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-api
  type: LoadBalancer
status:
  loadBalancer: {}
